workspace = { members = ["obfs-macro"] }
[package]
name = "obfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obfs-macro = {path = "./obfs-macro"}
